project_id = "pnuydoujbrpfhohsxndz"

[functions.unlock-episode]
verify_jwt = false

[functions.buy-coins]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.generate-covers]
verify_jwt = false

[functions.admin-manage-user]
verify_jwt = false